const categoryName = {
  mesas: 1,
  sillas: 2,
  sillones: 3,
};

const products = [
  {
    title: "Mesa De Centro",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-de-centro/mesa-de-centro-imageenvionment.png`,
    description: "Mesa De Centro Alaia De Madera Maciza De Acacia Con Acabado Natural 115cm x 65cm",
    price: 756,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-de-centro/mesa-de-centro-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-de-centro/mesa-de-centro-imagemeasures.png`,
    stock: 1,
    featured: true,
    measures: "Al 75 cm x An 120 cm x Pr 120 cm",
    style: "Colonia, Rústico",
    material: "Acacia, Hierro, Madera maciza",
    environment: "Living",
    slug: "mesa-de-centro",
    categoryId: categoryName.mesas,
  },
  {
    title: "Silla Doriane De Madera Maciza",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-doriane/silla-doriane-imageenvironment.png`,
    description:
      "La silla Doriane  de roble acabado natural y asiento de tela es una pieza artesanal hecha con madera maciza de roble sostenible, ratán trenzado a mano y un asiento con un tapizado efecto lino hidrorepelente.. Ideal para conseguir un comedor de tendencia con look natural gracias a su diseño clásico.",
    price: 444,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-doriane/silla-doriane-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-doriane/silla-doriane-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 82,5 cm x An 47 cm x Pr 51 cm",
    style: "Colonial, Rústico, Vintage",
    material: "Espuma, Madera, Ratán, Roble, Tela",
    environment: "Comedor",
    slug: "silla-doriane-de-madera-maciza",
    categoryId: categoryName.sillas,
  },
  {
    title: "Silla Konna Gris Oscuro ",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-kona/silla-kona-imageenvironment.png`,
    description:
      "La silla Konna con sus patas de madera maciza de fresno para cualquier ocasión. No hay nada que se agradezca más que unas sillas cómodas alrededor de una buena mesa. Con las sillas Konna, además de añadir estilo y marcar tendencia en tu comedor, tienes ese confort que esperas de las largas sobremesas.",
    price: 388,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-kona/silla-kona-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-kona/silla-kona-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 15 cm x An 45 cm x Pr 45 cm",
    style: "Moderno, Nórdico",
    material: "Comedor, Escritorio",
    environment: "Comedor",
    slug: "silla-konna-gris-oscuro",
    categoryId: categoryName.sillas,
  },
  {
    title: "Silla Nina Madera Maciza",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nina/imageenvironment.png`,
    description:
      "La silla Nina confeccionada de eucalipto y cuerda beige es un diseño donde la estructura de madera maciza de eucalipto y el trenzado del asiento se han trabajado a mano. Además, los materiales están tratados para aprovechar al máximo sus cualidades. Conócelas y disfruta de una pieza única.",
    price: 472,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nina/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nina/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 77 cm x An 53 cm x Pr 54 cm",
    style: "Moderno, Nórdico, Vintage",
    material: "Cuerda, Eucalipto, Madera maciza",
    environment: "Comedor, Escritorio, Exterior",
    slug: "silla-nina-madera-maciza",
    categoryId: categoryName.sillas,
  },
  {
    title: "Mesa Batilde Madera Maciza",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-batilde/mesa-batilde-imageenvionment.png`,
    description:
      "Todo lo bueno ocurre alrededor de una mesa. Así que, si quieres escogerla bien, apuesta por aquella que más hable de ti. La mesa Batilde es exclusiva como tú, al ser de madera maciza de caucho, con tonalidades y vetas únicas.",
    price: 496,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-batilde/mesa-batilde-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-batilde/mesa-batilde-imageemeasures.png`,
    stock: 1,
    featured: true,
    measures: "Al 74 cm x An 140 cm x Pr 70 cm",
    style: "Moderno, Nórdico",
    material: "Caucho, Madera maciza",
    environment: "Comedor",
    slug: "mesa-batilde-madera-maciza",
    categoryId: categoryName.mesas,
  },
  {
    title: "Mesa Redonda Maial",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-redonda-maial/mesa-redonda-maial-imageenvironment.png`,
    description:
      "¿Comedor pequeño? Welcome! La mesa Maial es la pieza ideal para espacios reducidos. Es de madera maciza de teca, con unas tonalidades que mantienen la luminosidad y amplitud de la estancia, y es redonda por lo que aprovechas al máximo el espacio.",
    price: 1040,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-redonda-maial/mesa-redonda-maial-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-redonda-maial/mesa-redonda-maial-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 77 cm x An 90 cm x Pr 90 cm",
    style: "Rústico",
    material: "Madera",
    environment: "Comedor",
    slug: "mesa-redonda-maial",
    categoryId: categoryName.mesas,
  },
  {
    title: "Sofá Narnia 3 Plazas",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-narnia/imageenvironment.png`,
    description:
      "Sofá 3 plazas tapizado con tela Lido tratamiento Teflón antimanchas. Asientos y respaldo desenfundables. Pies en madera de haya natural.",
    price: 1552,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-narnia/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-narnia/imagemeasures.png`,
    stock: 1,
    featured: true,
    measures: "Al 88 cm x An 192 cm x Pr 90 cm",
    style: "Nórdico",
    material: "Acero, Madera maciza, Tapizado Tela Antimanchas",
    environment: "Estar, Living",
    slug: "sofa-narnia-3-plazas",
    categoryId: categoryName.sillones,
  },
  {
    title: "Sofá Gilma 3 Plazas",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-gilma/imageenvironment.png`,
    description:
      "Un sofá ideal vivas solo o en compañía, con lugar para todos los de casa. El diseño del sofá Gilma con chaise longue, de líneas sencillas y corte contemporáneo, se ajusta a todo tipo de ambiente añadiendo estilo.",
    price: 2440,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-gilma/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-gilma/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 83 cm x An 260 cm x Pr 83 / 158 cm",
    style: "Moderno, Nórdico",
    material: "Madera maciza, Eucalipto, Tapizado Tela",
    environment: "Estar, Living",
    slug: "sofa-gilma-3-plazas",
    categoryId: categoryName.sillones,
  },
  {
    title: "Butaca Glam",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillones/butaca-glam/imageenvironment.png`,
    description:
      "Sillón tapizado con tela Varese tratamiento Teflón antimanchas. Pies en madera de haya natural. Cojín incluido.",
    price: 728,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillones/butaca-glam/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillones/butaca-glam/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto: 90 cm x Ancho: 73 cm x Fondo: 85 cm",
    style: "Moderno, Nórdico",
    material: "Madera maciza, Tapizado Tela",
    environment: "Estar, Living",
    slug: "butaca-glam",
    categoryId: categoryName.sillones,
  },
  {
    title: "Mesa Extensible Isbel",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-extensible-isabel/mesa-extensible-isbel-imageenvironment.png`,
    description:
      "Tu comedor, una de las estancias centrales de tu casa, merece lo mejor. Por eso, empieza por una buena mesa. Apuesta por la madera maciza de roble de la mesa Isbel y sus extensiones para los que no pueden faltar en las mejores ocasiones.",
    price: 1740,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-extensible-isabel/mesa-extensible-isbel-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-extensible-isabel/mesa-extensible-isbel-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 75 cm x An (140 - 220) cm x Pr 90 cm",
    style: "Moderno, Rústico",
    material: "	Madera maciza, Roble",
    environment: "Comedor, Estar",
    slug: "mesa-extensible-isbel",
    categoryId: categoryName.mesas,
  },
  {
    title: "Set Akemi De 2 Mesas De Centro",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/set-akemi/set-akemi-imageenvironment.png`,
    description:
      "Este set de vidrio texturizado es la pieza perfecta para los que soñaban con un salón de tendencia industrial y diseño geométrico. Con una mesa de 50 x 55 cm y otra de 100 x 50 cm, lo tienes todo para disfrutar de la estancia principal de tu casa.",
    price: 470,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/set-akemi/set-akemi-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/set-akemi/set-akemi-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Al 43/35 cm x An 100/50 cm x Pr 50/55 cm",
    style: "Industrial, Moderno",
    material: "Acero, Cristal",
    environment: "Living",
    slug: "set-akemi-de-2-mesas-de-centro",
    categoryId: categoryName.mesas,
  },
  {
    title: "Mesa Argo Roble Blanqueado",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-argo/mesa-argo-imageenvironment.png`,
    description:
      "Comidas familiares, ocasiones especiales, fiestas con los amigos… Los mejores momentos están alrededor de una buena mesa. Ten la mejor. Con Argo, de madera maciza de roble eco y patas de acero, añade diseño con los mejores materiales y acabados",
    price: 2550,
    image: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-argo/mesa-argo-image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/mesas/mesa-argo/mesa-argo-imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "	Alto 78 cm x Ancho 180 cm x Prof. 100 cm",
    style: "Moderno, Rústico",
    material: "	Acero, Madera, Roble",
    environment: "Comedor",
    slug: "mesa-argo-roble-blanqueado",
    categoryId: categoryName.mesas,
  },
  {
    title: "Sofá Noa 3 Plazas",
    imageenvironment:
      "https://f.fcdn.app/imgs/435826/www.kavehome.com.uy/kaveuy/1f1c/webp/catalogo/S719GC_02_2/900x1125/sofa-noa-3-plazas-con-almohadones-gris-patas-acabado-natural-230-cm.jpg",
    description:
      "La pieza principal de tu salón es eco. El sofá Noa tiene un diseño que, además de ofrecer confort con su efecto plumón, piensa en verde, ya que todo su tapizado se ha hecho 100% con PET, plástico reciclado recuperado del mar. Ideal para ti y tu ambiente.",
    price: 3700,
    image:
      "https://f.fcdn.app/imgs/a0def9/www.kavehome.com.uy/kaveuy/1ff6/webp/catalogo/S719GC_02_1/900x1125/sofa-noa-3-plazas-con-almohadones-gris-patas-acabado-natural-230-cm.jpg",
    imagemeasures:
      "https://f.fcdn.app/imgs/6e2311/www.kavehome.com.uy/kaveuy/28aa/webp/catalogo/S719GC_02_8/900x1125/sofa-noa-3-plazas-con-almohadones-gris-patas-acabado-natural-230-cm.jpg",
    stock: 1,
    featured: false,
    measures: "Alto 94 cm x Ancho 230 cm x Prof. 100 cm",
    style: "Moderno, Nórdico",
    material: "Espuma, Madera, Pino, Tela",
    environment: "Escritorio, Living",
    slug: "sofa-noa-3-plazas",
    categoryId: categoryName.sillones,
  },
  {
    title: "Sofá Galene De 3 Plazas",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-galene/imageenvironment.png`,
    description:
      "Un buen diseño por dentro y por fuera. Con el sofá Galene, además de tener un extra confort gracias a su efecto plumón, le haces un bien al planeta, ya que todo su relleno se ha hecho con PET, plástico reciclado recuperado del mar.",
    price: 2775,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-galene/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-galene/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto 94 cm Ancho 214 cm Prof. 96 cm",
    style: "Moderno, Nórdico",
    material: "Poliester",
    environment: "Living",
    slug: "sofa-galene-de-3-plazas",
    categoryId: categoryName.sillones,
  },
  {
    title: "Sofá Obo 3 Plazas",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-obo/imageenvironment.png`,
    description:
      "Sofá de estilo escandinavo tapizado en tela modelo Miss. Pespuntes decorativos en el respaldo. Pies de madera natural",
    price: 2080,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-obo/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillones/sofa-obo/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto 81  cm x Ancho 190  cm x Prof. 81  cm",
    style: "Minimalista, Moderno, Nórdico",
    material: "Tapizado/a, Tela",
    environment: "Estar, Living",
    slug: "sofa-obo-3-plazas",
    categoryId: categoryName.sillones,
  },
  {
    title: "Silla Croft - Gris Claro",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-croft/imageenvironment.png`,
    description:
      "Silla con brazos. Tapizada en tela, parte posterior del asiento acolchado. Pies de madera maciza de fresno",
    price: 525,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-croft/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-croft/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto 80 cm x Ancho 54 cm x Prof. 57 cm",
    style: "Moderno, Nórdico",
    material: "Antimanchas, Madera maciza, Tela",
    environment: "Comedor, Escritorio",
    slug: "silla-croft-gris-claro",
    categoryId: categoryName.sillas,
  },
  {
    title: "Silla Nayme - Beige",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nayme/imageenvironment.png`,
    description:
      "Todo lo bueno ocurre alrededor de una mesa. Así que, escoge bien las sillas y apuesta por aquellas que más hablen de ti. La silla Nayme es exclusiva como tú, al ser de madera maciza de caucho, con tonalidades y vetas únicas",
    price: 275,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nayme/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-nayme/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto 77 cm x Ancho 48 cm x Prof. 50 cm",
    style: "Moderno, Nórdico",
    material: "Caucho, Madera maciza",
    environment: "Comedor",
    slug: "silla-nayme-beige",
    categoryId: categoryName.sillas,
  },
  {
    title: "Silla Trise",
    imageenvironment: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-trise/imageenvironment.png`,
    description:
      "¿Comedor pequeño? Welcome! Gracias al diseño ligero de Trise, de madera con lacado natural, mantienes la luminosidad y sensación de amplitud en los espacios, además de añadirle estilo.",
    price: 345,
    image: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-trise/image.png`,
    imagemeasures: `${process.env.SUPABASE_BUCKET_URL}/sillas/silla-trise/imagemeasures.png`,
    stock: 1,
    featured: false,
    measures: "Alto 77 cm x Ancho 53  cm x Prof. 54 cm",
    style: "Vintage",
    material: "Caucho, Madera maciza",
    environment: "Comedor, Escritorio",
    slug: "silla-trise",
    categoryId: categoryName.sillas,
  },
];

module.exports = products;
